apiVersion: v1
kind: Service
metadata:
  name: nodejs-store-frontend
  labels:
    app: nodejs-store
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: nodejs-store
    tier: frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP